#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	# stub
	return

def configure(conf):
	# check for dedicated server build
	if conf.options.DEDICATED:
		return

def build(bld):
	if bld.env.DEDICATED:
		return

	libs = [ 'M' ]

	source = bld.path.parent.ant_glob(['client/*.c'])

	includes = ['.',
		'../common', '../api' ]

	bld.shlib(
		source   = source,
		target   = 'client',
		features = 'c',
		includes = includes,
		use      = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
